Imported Debian patch 8.13-2

diff --git a/tests/misc/timeout b/tests/misc/timeout
--- a/tests/misc/timeout
+++ b/tests/misc/timeout
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Validate timeout basic operation
 
-# Copyright (C) 2008-2010 Free Software Foundation, Inc.
+# Copyright (C) 2008-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,15 +16,11 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  timeout --version
-fi
-
-. $srcdir/test-lib.sh
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ timeout
 
 # no timeout
-timeout 1 true || fail=1
+timeout 10 true || fail=1
 
 # no timeout (suffix check)
 timeout 1d true || fail=1
@@ -33,13 +29,18 @@ timeout 1d true || fail=1
 timeout 0 true || fail=1
 
 # exit status propagation
-timeout 1 false && fail=1
-timeout 1 sh -c 'exit 2'
+timeout 10 sh -c 'exit 2'
 test $? = 2 || fail=1
 
 # timeout
-timeout 1 sleep 2
+timeout 1 sleep 10
 test $? = 124 || fail=1
+
+# kill delay. Note once the initial timeout triggers,
+# the exit status will be 124 even if the command
+# exits on its own accord.
+timeout -s0 -k1 1 sleep 10
+test $? = 124 && fail=1
 
 # Ensure `timeout` is immune to parent's SIGCHLD handler
 # Use a subshell and an exec to work around a bug in FreeBSD 5.0 /bin/sh.
@@ -47,7 +48,12 @@ test $? = 124 || fail=1
   # ash doesn't support "trap '' CHLD"; it knows only signal numbers.
   sig=`"$abs_top_builddir/src/kill" -l CHLD 2>/dev/null` && trap '' $sig
 
-  exec timeout 1 true
+  exec timeout 10 true
 ) || fail=1
+
+# Don't be confused when starting off with a child (Bug#9098).
+out=$(sleep 1 & exec timeout 2 sh -c 'sleep 3; echo foo')
+status=$?
+test "$out" = "" && test $status = 124 || fail=1
 
 Exit $fail
